import Head from 'next/head';

import MovieLayout from '@/layouts/MovieLayout';

import { getPopularApi } from '@/utils/api';
import { MovieType } from '@/interface';

interface Props {
  data: MovieType[];
}

export const getStaticProps = async () => {
  try {
    const res = await getPopularApi();
    const data = await res.json();

    return {
      props: { data: data.results },
    };
  } catch (err) {
    console.log(err);
  }
};

export const Home: React.FC<Props> = ({ data }) => {
  return (
    <>
      <Head>
        <title>The Movies</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MovieLayout movieList={data} />
    </>
  );
};

export default Home;
